name: Docker Image CI

on:
  push:
    tags:
      # match tags like v0.19.2
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      # Assuming here that new tags always correspond to higher versions. 
      # If a lower version tag is created, it will still receive the `latest` tag.
      run: |
        echo '${{github.ref_name}}'
        docker build . --file Dockerfile --tag gruhn/scryer-prolog:'${{github.ref_name}}' --tag gruhn/scryer-prolog:latest
